CREATE TABLE cars
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    make       VARCHAR(255),
    model      VARCHAR(255),
    price_from DECIMAL,
    price_to   DECIMAL,
    CONSTRAINT pk_cars PRIMARY KEY (id)
);